import type { PluginContracts } from './types.js';
import { contractsSchemaId, contractsVersion } from './version.js';

/**
 * Audit plugin contracts manifest
 * Level 2: Contracts типизация с as const для извлечения типов
 */
export const pluginContractsManifest = {
  schema: contractsSchemaId,
  pluginId: '@kb-labs/audit',
  contractsVersion,
  artifacts: {
    'audit.report.json': {
      id: 'audit.report.json',
      kind: 'json',
      description: 'Full JSON payload with per-check details.',
      pathPattern: '.kb/audit/report.json',
      mediaType: 'application/json',
      schemaRef: '@kb-labs/audit-contracts/schema#AuditReportSchema',
    },
    'audit.summary.md': {
      id: 'audit.summary.md',
      kind: 'markdown',
      description: 'Markdown summary generated by kb audit run.',
      pathPattern: '.kb/audit/summary.md',
      mediaType: 'text/markdown',
    },
    'audit.summary.txt': {
      id: 'audit.summary.txt',
      kind: 'text',
      description: 'Plain text summary for CI logs.',
      pathPattern: '.kb/audit/summary.txt',
      mediaType: 'text/plain',
    },
  },
  commands: {
    'audit:run': {
      id: 'audit:run',
      description: 'Run quality audit checks',
      examples: [
        'kb audit run',
        'kb audit run --scope packages/*',
        'kb audit run --strict --json',
      ],
    },
    'audit:list-checks': {
      id: 'audit:list-checks',
      description: 'List available audit checks',
      examples: ['kb audit list-checks', 'kb audit list-checks --json'],
    },
    'audit:show': {
      id: 'audit:show',
      description: 'Show last audit report',
      examples: ['kb audit show', 'kb audit show --json'],
    },
    'audit:clean': {
      id: 'audit:clean',
      description: 'Clean audit output directory',
      examples: ['kb audit clean'],
    },
  },
  api: {
    rest: {
      basePath: '/v1/plugins/audit',
      routes: {
        'audit.rest.checks': {
          id: 'audit.rest.checks',
          method: 'GET',
          path: '/checks',
          description: 'List available audit checks',
          response: {
            ref: '@kb-labs/audit-contracts/schema#AuditListChecksResponseSchema',
            format: 'zod',
          },
        },
        'audit.rest.report': {
          id: 'audit.rest.report',
          method: 'GET',
          path: '/report/latest',
          description: 'Get latest audit report',
          response: {
            ref: '@kb-labs/audit-contracts/schema#AuditReportSchema',
            format: 'zod',
          },
        },
      },
    },
  },
} as const satisfies PluginContracts;

// Извлекаем типы для использования в других местах
export type PluginArtifactIds = keyof typeof pluginContractsManifest.artifacts;
export type PluginCommandIds = keyof typeof pluginContractsManifest.commands;
export type PluginRouteIds = typeof pluginContractsManifest.api extends { rest: { routes: infer R } }
  ? R extends Record<string, any>
    ? keyof R
    : never
  : never;

