import { access, mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

type SetupContext = {
  cwd?: string;
  runtime?: {
    log?: (level: 'debug' | 'info' | 'warn' | 'error', message: string, meta?: Record<string, unknown>) => void;
  };
};

export async function run(ctx: SetupContext = {}) {
  const cwd = ctx.cwd ?? process.cwd();
  const auditDir = join(cwd, '.kb', 'audit');
  const reportsDir = join(auditDir, 'reports');
  const created: string[] = [];

  await mkdir(reportsDir, { recursive: true });
  created.push(reportsDir);

  const gitignorePath = join(auditDir, '.gitignore');
  const readmePath = join(auditDir, 'README.md');

  async function ensureFile(path: string, contents: string) {
    try {
      await access(path);
    } catch {
      await writeFile(path, contents, 'utf-8');
      created.push(path);
    }
  }

  await ensureFile(
    gitignorePath,
    ['# Ignore generated audit artifacts', 'report.json', 'summary.*', 'reports/', ''].join('\n')
  );

  await ensureFile(
    readmePath,
    [
      '# KB Labs Audit workspace',
      '',
      'This directory stores reports and summaries generated by `kb audit run`.',
      'Do not commit these files unless you intentionally share the audit evidence.',
      '',
    ].join('\n')
  );

  ctx.logger?.info('Audit setup completed', { cwd, created });

  return {
    ok: true,
    auditDir,
    created,
  };
}


